 
swagger: '2.0'
info:
  title: HTML Injection
  description: |
    Teste
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified'"><h1><marquee>Hacked</marquee></h1>
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
