swagger: '2.0'
info:
  title: HTML Injection
  description: |
    Teste
paths:
  /accounts:
    get:
      responses:
        '200':
          description: '"><h1><marquee>Hacked</marquee></h1>
      tags:
        - accounts
